// Code generated by golang.gen. DO NOT EDIT.

package db

import (
	"time"
)

type User struct {
	ID        int64     `db:"id"`
	Name      string    `db:"name"`
	Email     string    `db:"email"`
	Bio       *string   `db:"bio"`        // nullable text -> *string
	CreatedAt time.Time `db:"created_at"` // NOT NULL timestamptz
}
