// Code generated by golang.gen. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
)

const getUserSQL = `-- name: GetUser :one
SELECT id, name, email, bio, created_at
FROM users
WHERE id = $1
`

type GetUserParams struct {
	ID int64
}

func (q *Queries) GetUser(ctx context.Context, params GetUserParams) (User, error) {
	rows, err := q.db.Query(ctx, getUserSQL, params.ID)
	if err != nil {
		return User{}, err
	}

	return pgx.CollectOneRow(rows, pgx.RowToStructByName[User])
}

const listUsersSQL = `-- name: ListUsers :many
SELECT id, name, email
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID    int64  `db:"id"`
	Name  string `db:"name"`
	Email string `db:"email"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsersSQL)
	if err != nil {
		return nil, err
	}

	return pgx.CollectRows(rows, pgx.RowToStructByName[ListUsersRow])
}

const createUserSQL = `-- name: CreateUser :one
INSERT INTO users (name, email, bio)
VALUES ($1, $2, $3)
RETURNING id, name, email, bio, created_at
`

type CreateUserParams struct {
	Name  string
	Email string
	Bio   pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, params CreateUserParams) (User, error) {
	rows, err := q.db.Query(ctx, createUserSQL, params.Name, params.Email, params.Bio)
	if err != nil {
		return User{}, err
	}

	return pgx.CollectOneRow(rows, pgx.RowToStructByName[User])
}

const updateUserSQL = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, email = $3
WHERE id = $1
`

type UpdateUserParams struct {
	ID    int64
	Name  string
	Email string
}

func (q *Queries) UpdateUser(ctx context.Context, params UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUserSQL, params.ID, params.Name, params.Email)
	return err
}

const deleteUserSQL = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

type DeleteUserParams struct {
	ID int64
}

func (q *Queries) DeleteUser(ctx context.Context, params DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUserSQL, params.ID)
	return err
}

const findUserByEmailSQL = `-- name: FindUserByEmail :one
SELECT id, name, email, bio, created_at
FROM users
WHERE email = $1
`

type FindUserByEmailParams struct {
	Email string
}

func (q *Queries) FindUserByEmail(ctx context.Context, params FindUserByEmailParams) (User, error) {
	rows, err := q.db.Query(ctx, findUserByEmailSQL, params.Email)
	if err != nil {
		return User{}, err
	}

	return pgx.CollectOneRow(rows, pgx.RowToStructByName[User])
}
